### PR TITLE
Ensure built-in roles are always present; #3200

### LINKED ISSUE #3200: Error editing/creating channels
**Description of the problem**

**How To Reproduce**

**Error Messages**

<pre>

Warning

Invalid argument supplied for foreach()

ee/ExpressionEngine/Controller/Channels/Channels.php, line 1627

Severity: E_WARNING
Warning

Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)

ee/legacy/core/Input.php, line 268

Severity: E_WARNING
Warning

Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)

ee/legacy/libraries/Functions.php, line 458

Severity: E_WARNING
<code>

</code></pre>

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: [7.2.12]
 - PHP Version [e.g. 7.4]

**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by intoeetive**
Ensure built-in roles are always present; closes #3200

### CODE REVIEW

File: system/ee/installer/updates/ud_7_04_00.php [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+        }
+
+        return true;
+    }
+
+    // in some very old EE versions is was possible to delete built-in member groups
+    // here we make sure the required roles are in place
+    private function ensureBuiltinRoles()
+    {
+        $rolesQuery = ee('Model')->get('Role')->fields('role_id')->filter('role_id', 'IN', [1, 2, 3, 4, 5]);
```
Comment (bryannielsen) [inline system/ee/installer/updates/ud_7_04_00.php:46]: @intoeetive Is it necessary for the built-in roles to have these `role_id`s 1-5?  Or should we be looking to ensure the role `short_name`s are populated and use whatever role_ids are available in the case that custom roles have been created?  Or were there always role_ids for 1-5 and any custom roles would have started at id 6 so this is safe to do?

Comment (intoeetive) [reply system/ee/installer/updates/ud_7_04_00.php:46]: Yes, the numbers are necessary (in fact, we even have them as constants)

**Review by matthewjohns0n — APPROVED** [review]
