### PR TITLE
fix updating legacy fields

### LINKED ISSUE #1729: EE2 -> 6.2 Upgrade Breaks ~ version 4.0.5
**Description of the problem**

When upgrading an EE site from v2.11.9 to v6.2.1, the upgrade process dies with a 500 error ~ version 4.0.4.

The upgrade process goes smoothly until reaching version 4.0.4. When attempting to run that upgrade, the browser crashes with a 500 error. I don't get any context on what occurs, and nothing is added to the PHP logs or displayed on screen.

If I upgrade to 6.1.6 first, and then to 6.2.1, the upgrade goes fine.

**How To Reproduce**

1. Get an EEv2.11.9 site.
2. Run typical upgrade steps for an EE2 => EE6 upgrade.

Video walkthrough here: https://youtu.be/CogkgVHnxEI

**Environment Details:**
 - Version: 2.11.9 => 6.2.1
 - PHP Version 7.3
 - MySQL Version 5.7
 - OS: Ubuntu
 - Web Server: nginx

**Possible Solution**

Unfortunately, I don't have much other context. I am not able to see anything in the logs re: to this. Not sure if its related to [this change?](https://github.com/ExpressionEngine/ExpressionEngine/commit/6092aed47865ba6a50708670f997f85ed504a1d7)

### PR DESCRIPTION
**Pull request by intoeetive**
EECORE-1621

fixes #1729

### CODE REVIEW

File: system/ee/installer/updates/ud_4_00_05.php [hunk 1]
```diff
@@ -44,7 +44,7 @@ public function do_update()
     private function fixGridModifierParsing()
     {
         $grid_fields = ee('Model')->get('ChannelField')
-            ->fields('field_id')
+            ->fields('field_id', 'legacy_field_data')
```
Comment (TomJaeger) [inline system/ee/installer/updates/ud_4_00_05.php:47]: @intoeetive So What is this actually solving?

Comment (intoeetive) [reply system/ee/installer/updates/ud_4_00_05.php:47]: `$field->getDataStorageTable(),` is using `legacy_field_data`, so it needs to be fetched to make things work properly.

@dougblackjr has confirmed this fix works for him

**Review by TomJaeger — APPROVED** [review]
