### PR TITLE
Release/5.3.1

### LINKED ISSUE #147: System online/offline status should not be altered by automatic updates.
If the system is set to be offline prior to starting an update, I expect it to stay that way after the update is done.

Currently the system is set to be online after an update without asking for confirmation or informing the user.

### LINKED ISSUE #188: Image Manipulation with Watermark
**Description of the problem**
Having a watermark on an image manipulation causes error on upload. The file DOES upload to the server, but errors are generated. 

**How To Reproduce**
1. Create a watermark using a transparent png file
2. Assign that watermark to an image manipulation in an upload directory: 
   Type: Image
    Alignment: Bottom
    Padding: 0
    Offset:0 0
    Path: as needed
    Opacity: 100
    Image Transparency Map: 2, 2
3. Upload a file to the directory

**Error Messages**

Warning
A non-numeric value encountered
ee/legacy/libraries/Image_lib.php, line 951

Severity: E_WARNING
Warning
A non-numeric value encountered
ee/legacy/libraries/Image_lib.php, line 952

Severity: E_WARNING
Warning
A non-numeric value encountered
ee/legacy/libraries/Image_lib.php, line 957

Severity: E_WARNING
Warning
A non-numeric value encountered
ee/legacy/libraries/Image_lib.php, line 958

Severity: E_WARNING
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/legacy/core/Input.php, line 238

Severity: E_WARNING
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/legacy/core/Input.php, line 238

Severity: E_WARNING
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/legacy/libraries/Functions.php, line 393

Severity: E_WARNING

</code></pre>

**Environment Details:**
 - Version: 5.2.2
 - PHP Version 7.2.13
 - MySQL Version 5.5
 - OS: macOS
 - Web Server: Apache

### LINKED ISSUE #190: Omitting the return parameter for the {exp:consent:form} tag doesn't redirect to same page as consent submitted on
**Description of the problem**
According to the [docs](https://docs.expressionengine.com/latest/add-ons/consent.html#return) the consent form should return to the page it was submitted when the return paramter is omitted:

{exp:consent:form consent='ee:cookies_functionality|ee:cookies_performance'}

However, the above code always returns to the homepage so you actually have to use:

{exp:consent:form return="{current_path}" consent='ee:cookies_functionality|ee:cookies_performance'}

which does give the desired result but is inconsistent with the documentation. 

Debugging points to decrypt() returning '' in particular openssl_decrypt

**How To Reproduce**

Make a consent form like below and 'agree' and you will be taken to the homepage and not the page you were on.

`{if ! consent:has_responded:ee:cookies_functionality}
	{exp:consent:form return="{current_path}" consent='ee:cookies_functionality|ee:cookies_performance'}
		{consents}<input type="hidden" name="{consent_short_name}" value="y">{/consents}
		<div class="consent">
			<div class="wrapper"><p>We use cookies to help make our site work properly and to analyze how our site is used. Some are optional, but none contain your personal information. You can view our <a href="/cookie-policy">cookies policy</a>, manage your <a href="/account/cookie-preferences">cookie preferences</a>, or consent and dismiss this banner by clicking agree:</p><p>
				  <button class="btn">Agree</button>
				</p>
			</div>
		</div>
	{/exp:consent:form}
{/if}`

**Environment Details:**
 - Version: [e.g. 5.1.2]
 - PHP Version [7.1]
 - MySQL Version [5.6.43]
 - OS: [Ubuntu Linux/CentOS]
 - Web Server: [Apache]

### LINKED ISSUE #248: The after_channel_entry_save event hook is called twice for every add-on using it
**Description of the problem**
It appears the `after_channel_entry_save` hook is getting called twice for every add-on using it, even if there is only 1 row per add-on in the `exp_extensions` table for the hook. 

**How To Reproduce**
Install an add-on using that hook, step debug, or log to file inside the add-on's method using the hook and you'll see it gets called twice every time an entry is saved. I tested this with 1 add-on installed, then a 2nd add-on, and they both have their `after_channel_entry_save` hook called twice. I also tested this in two different EE environments. One using 5.2.3, and another 5.2.4.

**Environment Details:**
 - Version: 5.2.3 & 5.2.4
 - PHP Version 7.2
 - MySQL Version 5.6
 - OS: macOS
 - Web Server: Apache (vagrant machine)

### LINKED ISSUE #292: Page URI and page template are not deletable in EE 5.2.6
With a fresh install of ExpressionEngine 5.2.6 with the default theme installed i'm unable to delete the Page URI or the Page template selection once i have entered one and saved the entry. I can change the Page URI and also the Page template but you cannot delete it. If you try to delete it and save the entry the value is still in the Page URI input field after browser page refresh.

### LINKED ISSUE #321: Entry not saving URI unless a Template has been selected
I have created a Channel intended to be used only as Page entries. I hadn’t selected a Default Template in the Pages Add-On settings for this Channel. I have created a Layout for the Channel, but had hidden the Template field.

When creating the Entry, I gave the URI a value, but it wouldn’t store that value when saving the Entry. It took me a while to figure out that it only stores the URI if you have selected a Template for the Entry.

Maybe we need some kind of Error Alert to highlight if a Template hasn’t been selected, to make it more obvious? This might be a sticky one for newbies.

### LINKED ISSUE #337: Entries with url_title of "n" not displaying
**Description of the problem**
I've found that trying out a specific Entries' data, whose url_title is "n" isn't working.
I need to use this url_title as it relates to the North London postcode region.

**How To Reproduce**
{exp:channel:entries channel="postcode" url_title="n" dynamic="no"}
	{title}
{/exp:channel:entries}

**Error Messages**
Just a blank output.

**Environment Details:**
 - Version: 5.3.0
 - PHP Version 7.1

### LINKED ISSUE #346: PHP 7.3 issue -strpos(): Non-string needles will be interpreted as strings in the future.
**Description of the problem**
I’ve been getting this warning quite a bit on one of my sites: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior. ee/legacy/libraries/channel_entries_parser/Parser.php, line 314

**Environment Details:**
 - Version: 5.3.0
 - PHP Version: 7.3
 - MySQL Version: 5.7
 - OS: macOs
 - Web Server: Apache

### LINKED ISSUE #382: TypeError: Cannot read property 'label' of undefined (Line 171)
**Description of the problem**

I had the weired issue on my EE site today. in MSM sites, File field not working. it shows me error on 171 line.

**How To Reproduce**

I have had many file fields including normal and in Grid. In main site, it works good. However in MSM site I get this error.

**Environment Details:**
 - Version: [5.3.0]
 - PHP Version [7.1]
 - OS: Linux
 - Web Server: Apache

**Possible Solution**

I found suspected code in file: themes/ee/asset/javascript/compressed/fields/file/drag_and_drop_upload.js

where it says:
<pre><code>
{
    key: "getDirectoryName",
    value: function(e) {
        return "all" == e ? null : (e = EE.dragAndDrop.uploadDesinations.find(function(t) {
            return t.value == e
        }), e.label)
    }
}
</code></pre>

e.label is not exists. I return e and it work for me.

image

### PR DESCRIPTION
**Pull request by dougblackjr**
## Overview

Release candidate for 5.3.1.

This offers a number of bug fixes and compatibility updates, including PHP7.4 compatibility.

NOTE: This does require a minimum PHP version of 5.6.

## LIST OF ISSUES/FIXES:
dcba538a60 Merging bug/pages-module-not-removing-uris, resolves #292
8f3886d664 Merging bug/label-typeerror-382, resolves #382
0e41a9989a Merging bug/346-fix-strpos-warning, resolves #346
8394beac4f Merging bug/337-url-title-n, resolves #337
32e17440d2 Merging bug/248-hook-firing-twice, resolves #248
c598e670ea Merging bug/190-consent-return, resolves #190
9abbea74f2 Merging bug/188-image-manipulation-warnings, resolves #188
c536789a17 Merging bug/147-system-on-by-update, resolves #147
1b1c946cfc Merge branch '321/pages-uri-template-validation' into release/5.3.1, resolves #321
d7e4615cb6 Adding non-duplicated fix from rjpdev:stability (#360)
67726df4e2 Fixes MSM JS error, resolves #382
5a7a8ae96e PHP 7.4 compatibility

## Nature of This Change

- [X] 🐛 Fixes a bug
- [ ] 🚀 Implements a new feature
- [X] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [X] Yes
- [ ] No

## Documentation
- changelogs/minor.rst (5.3.1)

Thanks to @rjpdev and @litzinger for their help on this!

### CODE REVIEW

File: system/ee/legacy/libraries/Template.php [hunk 1]
```diff
@@ -1903,6 +1905,13 @@ public function process_tags()
 	 */
 	public function fetch_param($which, $default = FALSE)
 	{
+
+		if(in_array($which, $this->ignore_fetch)) {
+
+			return $this->tagparams[$which];
```
Comment (obfuscode) [inline system/ee/legacy/libraries/Template.php]: This throws a PHP "undefined index" Notice. I setup a template with a basic channel entries loop with `title` and `url_title`.

Comment (dougblackjr) [reply system/ee/legacy/libraries/Template.php]: @obfuscode Fixed in latest commit.
