### PR TITLE
Resolved #4141 where password reset pages were not using custom branded logo

### LINKED ISSUE #4141: Branding doesn't change the logo in places like "Remind me" in the admin panel pages
**Description of the problem**
I've added the branding in the settings and I see it when I log into the admin panel. But pages like the "remind me" has an SVG of the ExpressionEngine Logo and not the branding one. 

**How To Reproduce**
1. upload logo to the branding section of the cms
2. log out of the CMS and click the "Remind me" - ExpressionEngine log appears and not the branding.

### PR DESCRIPTION
**Pull request by intoeetive**
Resolved #4141 where password reset pages were not using custom branded logo

### CODE REVIEW

File: system/ee/ExpressionEngine/View/account/forgot_password.php [hunk 1]
```diff
@@ -1,23 +1,27 @@
 <?php $this->extend('_templates/login'); ?>
 
 <div class="login__logo">
+    <?php if (ee('pro:Access')->hasRequiredLicense() && ee()->config->item('login_logo')) : ?>
+    <img src="<?=ee()->config->item('login_logo')?>" alt="Powered by ExpressionEngine&reg;">
```
Comment (bryannielsen) [inline system/ee/ExpressionEngine/View/account/forgot_password.php]: Should we be putting "Powered by ExpressionEngine" here?  I think the Site Name might be a more appropriate alt/title text to go along with the custom logo

Comment (intoeetive) [reply system/ee/ExpressionEngine/View/account/forgot_password.php]: That makes sense. Changing here and also in other places.

**Review by bryannielsen — APPROVED** [review]
