### PR TITLE
Resolved #3654 where incorrect fieldtype options were shown on load

### LINKED ISSUE #3654: Stray elements appearing in EE6 field definition screens
**Description of the problem**
In EE6 a few stray elements are appearing in Field definition panels.
For Text Input field in normal use you see an extra "Show File Chooser" toggle
image
In the modal / pop up version of this same thing (i.e. add a text field but via field group edit panel) you see also some elements relating to relationship fields.
image

**How To Reproduce**
Create a field assign to text input and scroll down.
FWIW behaviour confirmed by @murtaugh on separate EE6 instance.

**Environment Details:**
 - Version: 6.4.13
 - PHP Version 8.1.21
 - Web Server: ddev / nginx

### PR DESCRIPTION
**Pull request by bryannielsen**
Resolved #3654 where incorrect fieldtype options were shown on load.

EE6 version of #4202

### CODE REVIEW

File: system/ee/ExpressionEngine/Controller/Fields/Fields.php [hunk 1]
```diff
@@ -865,6 +865,16 @@ private function form(ChannelField $field = null)
             }
 
             $field_options = $dummy_field->getSettingsForm();
+            // When fieldtype settings contain fields with their own group toggles
+            // we need to loop through them and append the fieldtype group name
+            foreach ($field_options as &$option) {
+                foreach ($option['settings'] ?? [] as $key => $setting) {
```
Comment (intoeetive) [inline system/ee/ExpressionEngine/Controller/Fields/Fields.php]: EE 6.x still supports PHP 5.6, and `??` operator was added in 7.0, so this code will cause issues

**Review by intoeetive — DISMISSED** [review]

**Review by robinsowell — APPROVED** [review]
worked in testing on v6
